var Anzu={};Anzu.ui={};
Anzu.core=function(){function j(){var d={Cd:65.4,"Cd#":69.3,Dd:73.425,"Dd#":77.775,Ed:82.4,Fd:87.3,"Fd#":92.5,Gd:98,"Gd#":103.825,Ad:55,"Ad#":58.275,Bd:61.7375},b;for(b=2;b<=9;b++)for(var h in d)g[h.replace("d",b.toString(10))]=g[h.replace("d",(b-1).toString(10))]*2}var g={A1:55,"A1#":58.275,B1:61.7375,C1:65.4,"C1#":69.3,D1:73.425,"D1#":77.775,E1:82.4,F1:87.3,"F1#":92.5,G1:98,"G1#":103.825};j();return{convertToPitch:function(d){return g[d]},audioStream:$("body"),samplingRate:22050,version:"0.0.1"}}();
function IsGecko(){if(navigator)if(navigator.userAgent)if(navigator.userAgent.indexOf("Gecko/")!=-1)return true;return false};Anzu.wave=function(){function j(d){return String.fromCharCode(d>>0&255,d>>8&255)}function g(d){return String.fromCharCode(d>>0&255,d>>8&255,d>>16&255,d>>24&255)}return{generator:{createSquareSignal:function(d,b){var h,e,c;c=0;d=Math.round(d*22050);var a=b*2*Math.PI/22050;h=new Array(d);for(b=0;b<d;b++){e=Math.sin(c);e=e>0?0.7:-0.7;h[b]=~~(e*32767);c+=a}return h},createSinSignal:function(d,b){var h,e,c;c=0;d=Math.round(d*22050);var a=b*2*Math.PI/22050;h=new Array(d);for(b=0;b<d;b++){e=Math.sin(c);
h[b]=~~(e*32767);c+=a}return h},createSawtoothSignal:function(d,b){var h,e,c;c=0;d=Math.round(d*22050);var a=22050/b;h=new Array(d);for(b=0;b<d;b++){if(c>a)c-=a;e=c*2/a-1;h[b]=~~(e*32767);c+=1}return h},createTriangleSignal:function(d,b){var h,e,c;c=0;d=Math.round(d*22050);var a=22050/b;h=new Array(d);for(b=0;b<d;b++){if(c>a)c-=a;e=c*2/a-1;e=(Math.abs(e)-0.5)*2;h[b]=~~(e*32767);c+=1}return h},createWhiteNoiseSignal:function(d){var b,h,e;d=Math.round(d*22050);h=new Array(d);for(b=0;b<d;b++){e=Math.random()*
2-1;h[b]=~~(e*32767)}return h}},mixSignal:function(d,b,h){var e,c,a;c=b.length;h=Math.floor(h);for(e=0;e<c;e++){a=d[e+h]+b[e];d[e+h]=a}},mixSignalV:function(d,b,h,e){var c,a,k;a=b.length;h=Math.floor(h);for(c=0;c<a;c++){k=d[c+h]+~~(b[c]*e);d[c+h]=k}},convertToBinary:function(d){var b,h,e;h=d.length;for(b=0;b<h;b++){e=d[b];e=e>393204?393204:e<-393204?-393204:e;d[b]=String.fromCharCode((e+393204)/786408*256)}return d.join("")},convertToURL:function(d){var b;b="WAVEfmt ";b+=g(16);b+=j(1);b+=j(1);b+=
g(22050);b+=g(22050);b+=j(1);b+=j(8);b+="data";var h;h=g(d.length);b+=h;h="RIFF";h+=g(b.length+d.length);return"data:audio/wav;base64,"+Base64.encode(h+b+d)}}}();Anzu.mixer=function(){function j(){if(!h)return false;var e=0;for(var c in g)e++;return e===0}var g={},d,b,h=false;return{init:function(e){d=e;g={};h=false},addQueue:function(e){g[e.key]=e.info},finishAddQueues:function(){h=true;j()&&b()},finishQueue:function(e){var c=e.key;Anzu.wave.mixSignalV(d,e.signals,g[c].start,g[c].volume);delete g[c];j()&&b()},setCallback:function(e){b=e}}}();Anzu.Score=function(){return function(j){if(typeof j==="string")try{j=JSON.parse(j)}catch(g){alert("Parse Error");console.log(g)}for(var d=[],b,h,e,c=0;c<j.tracks.length;c++)d[c]=Anzu.Track(j.tracks[c]);return{bpm:j.bpm,addTrack:function(a){d.push(a)},updateTrack:function(a,k){d[a]=k},setCallback:function(a){h=a},setAfterCallback:function(a){e=a},play:function(a){var k,l,m,n,o,q,p,v,w;w=Anzu.core.samplingRate;l=d.length;p=this.getEndTime();q=60/this.bpm;v=Math.ceil((p-a)*q*w);if(v<=0)v=1;n=new Array(v);
for(k=0;k<v;k++)n[k]=0;Anzu.mixer.init(n);Anzu.mixer.setCallback(function(){var u=Anzu.wave.convertToBinary(n);u=Anzu.wave.convertToURL(u);b=new Audio(u);Anzu.core.audioStream.append($(b));b.volume=1;u=u=o=n=null;if(h)var t=setInterval(function(){if(b.currentTime>0.1){clearInterval(t);h(q,p-a,b.currentTime/q)}},100);e&&setTimeout(function(){e();if(b){b.pause();b.src=undefined;$(b).remove()}},v/w*1E3+100);b.play()});for(k=0;k<l;k++){m=d[k];o=m.getSignalOpt(n,a,q)}Anzu.mixer.finishAddQueues()},stop:function(){b.pause();
$(b).remove()},getEndTime:function(){var a,k,l,m;k=d.length;for(a=m=0;a<k;a++){l=d[a];l=l.getLastNote();l=l.begin+l.length;if(l>m)m=l}return m},getTrack:function(a){return d[a]},dump:function(){return'{"tracks":['+d.map(function(a){return a.dump()}).join(",")+'],"bpm":'+this.bpm+',"maxID":'+this.getMaxID()+"}"},changeBPM:function(a){this.bpm=a},getMaxID:function(){for(var a,k,l=a=0;l<d.length;l++){k=d[l].getMaxID();if(k>a)a=k}return a},getOnionTracks:function(){for(var a=[],k=0;k<d.length;k++)d[k].isOnion()&&
a.push(d[k]);return a}}}}();
Anzu.Track=function(){return function(j){if(typeof j==="string")j=JSON.parse(j);var g,d,b=0.5,h=false;g=j.notes;for(var e=0;e<g.length;e++)g[e]=Anzu.Note(g[e]);if(j.tone.match(/\.js/)){d="Anzu.SequareWave";Anzu.tone.addUserTone(j.tone,function(c){d=c})}else d=j.tone;b=j.volume?Math.abs(j.volume)>1?0.5:j.volume:0.5;return{addNote:function(c){g.push(c)},deleteNote:function(c){for(var a=0;g.length;a++)if(g[a]===c){g.splice(a,1);return}},deleteUnlinkNotes:function(){for(var c=g.length-1;c>=0;c--)g[c].divID||
g.splice(c,1)},_notes:function(){return g},deleteNoteFromDiv:function(c){for(var a=0;a<g.length;a++)if(g[a].divID===parseInt(c.id,10)){Anzu.eventManager.add("deleteNote",g[a]);g.splice(a,1);return}},changeNote:function(c){for(var a=0;a<g.length;a++)if(g[a].divID===parseInt(c.id,10)){g[a].setDiv(c);Anzu.eventManager.add("changeNote",g[a]);return}},setTone:function(c){d=c},getTone:function(){return d},getLastNote:function(){if(g.length===0)return Anzu.Note({begin:0,length:0,key:"A4"});g.sort(function(c,
a){return c.begin+c.length-(a.begin+a.length)});return g[g.length-1]},getSignal:function(c,a){var k=Anzu.core.samplingRate,l,m,n,o,q,p;p=Anzu.tone.getTone(d);m=g.length;l=this.getLastNote();n=Math.ceil((l.begin+l.length)*a*k);l=new Array(n);for(o=0;o<n;o++)l[o]=0;for(o=0;o<m;o++){n=g[o];if(!(n.begin<c)){q=n.getSignal(p,a);Anzu.wave.mixSignal(l,q,(n.begin-c)*a*k)}}return l},getSignalOpt:function(c,a,k){var l=Anzu.core.samplingRate,m,n,o,q,p;p=Anzu.tone.getTone(d);n=g.length;m=this.getLastNote();Math.ceil((m.begin+
m.length)*k*l);if(typeof p==="function")for(m=0;m<n;m++){o=g[m];if(!(o.begin<a)){q=o.getSignal(p,k);Anzu.wave.mixSignalV(c,q,(o.begin-a)*k*l,b)}}else for(m=0;m<n;m++){o=g[m];if(!(o.begin<a)){q=m+"@"+o.begin+"@"+o.length;Anzu.mixer.addQueue({key:q,info:{start:(o.begin-a)*k*l,volume:b}});o.getSignalASync(p,k,q)}}return c},isOnion:function(){return h},setOnion:function(c){h=c},getVolume:function(){return b},setVolume:function(c){b=c},getMaxID:function(){for(var c,a,k=c=0;k<g.length;k++){a=g[k].divID;
if(a>c)c=a}return c},dump:function(){return'{"notes":['+g.map(function(c){return c.dump()}).join(",")+'],"tone":"'+Anzu.tone.getToneDumpName(d)+'","volume":'+b+"}"}}}}();
Anzu.Note=function(){return function(j){j=!j?{}:j;return{begin:j.begin,length:j.length,key:j.key,divID:parseInt(j.id),setDiv:function(g){this.div=g;var d,b,h;d=parseInt(g.style.top,10);b=parseInt(g.style.left,10);h=parseInt(g.style.width,10);this.begin=b/100;this.length=h/100;this.key=Anzu.ui.posKeyList[Math.floor((d+5)/20)*20];this.divID=parseInt(g.id,10)},getSignal:function(g,d){return g(d*this.length,Anzu.core.convertToPitch(this.key))},getSignalASync:function(g,d,b){g.call(d*this.length,Anzu.core.convertToPitch(this.key),
b)},dump:function(){return'{"begin":'+this.begin+',"length":'+this.length+',"key":"'+this.key+'","id":"'+this.divID+'"}'}}}}();Anzu.tone=function(){function j(e){var c={};if(typeof e==="string"){e=e.split(",");var a,k=e.length;for(a=0;a<k-1;a++)e[a]=parseInt(e[a],10);a=e.pop();c.key=a;c.signals=e}else c=e;return c}var g={},d={},b=Anzu.wave.createSquareSignal,h={};g["Anzu.SquareWave"]=Anzu.wave.generator.createSquareSignal;g["Anzu.SineWave"]=Anzu.wave.generator.createSinSignal;g["Anzu.SawtoothWave"]=Anzu.wave.generator.createSawtoothSignal;g["Anzu.WhiteNoise"]=Anzu.wave.generator.createWhiteNoiseSignal;return{addTone:function(e,
c){g[e]=c},getToneList:function(){var e=[],c;for(c in g)e.push(c);for(c in d)e.push(c);return e},getToneDumpName:function(e){if(g[e])return e;else if(d[e])return h[e];return"Anzu.SequareWave"},getTone:function(e){var c=g[e];if(c)return c;else{var a=d[e];return a?{call:function(k,l,m){(function(n){parseInt(n);var o;a.onmessage=function(){return function(q){q=j(q.data);Anzu.mixer.finishQueue({key:q.key,signals:q.signals})}}(n);o=IsGecko()?0:1;a.postMessage(k+"|"+l+"|"+Anzu.core.samplingRate+"|"+n+"|"+
o)})(m)}}:Anzu.wave.createSquareSignal}},getDefaultTone:function(){return b},setDefaultTone:function(e){if(g[e])b=this.getTone(e);else if(d[e]){var c=d[e];b={call:function(a,k,l){c.onmessage=function(n){n=j(n.data).signals;a(n)};var m=IsGecko()?0:1;c.postMessage(k+"|"+l+"|"+Anzu.core.samplingRate+"|once|"+m)}}}return g["Anzu.SeguareWave"]},addUserTone:function(e,c,a){for(var k in h)h.key===e&&c(k);var l=new Worker("js/anzu/usertone.js");l.onmessage=function(m){m=m.data.split("@")[0];d[m]=l;h[m]=e;
c&&c(m);Anzu.player.refreshTone()};l.onerror=function(m){a(m.message)};l.postMessage("init|"+e)}}}();Anzu.eventManager=function(){var j=[],g=0,d=0;return{add:function(b,h){j.push({type:b,value:h,track:g})},changeCurrentTrack:function(b){g=b},setDivID:function(b){d=b},getDivID:function(){return d},incDivID:function(){if(typeof wave!=="undefined"){d=parseInt(wave.getState().get("divID"),10)+1;wave.getState().submitDelta({divID:d})}else d+=1},init:function(b){d=typeof wave!=="undefined"&&wave.getState().get("divID")?wave.getState().get("divID"):b?b:0}}}();$(function(){Anzu.player.score=Anzu.Score('{"tracks" : [ { "notes" : [], "tone" : "Anzu.SquareWave"}, { "notes" : [], "tone" : "Anzu.SquareWave"}, { "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"},{ "notes" : [], "tone" : "Anzu.SquareWave"} ], "bpm" : 120}');
$("#back1Button").button({icons:{primary:"ui-icon-seek-first"},text:false}).click(function(){Anzu.player.moveBar(-400)});$("#back4Button").button({icons:{primary:"ui-icon-seek-prev"},text:false}).click(function(){Anzu.player.moveBar(-100)});$("#playstopButton").button({icons:{primary:"ui-icon-play"},text:false}).click(function(){Anzu.player.playstop()});$("#play1Button").button({icons:{primary:"ui-icon-seek-next"},text:false}).click(function(){Anzu.player.moveBar(+100)});$("#play4Button").button({icons:{primary:"ui-icon-seek-end"},
text:false}).click(function(){Anzu.player.moveBar(+400)});$("#bpmButton").button({}).click(function(){$("#bpmDialog").dialog("open")});$("#saveButton").button({}).click(function(){Anzu.player.openExportDialog()});$("#toneButton").button({}).click(function(){$("#userToneForm").val("http://");$("#userToneForm").removeClass("ui-state-error");$("#userToneFormHelper").html("");$("#userToneFormHelper").removeClass("ui-state-highlight");$("#addToneDialog").dialog("open")});$("#onionCheckBox").button({icons:{primary:"ui-icon-check"}}).click(function(){Anzu.player.setOnion(this.checked)});
$("#bpmDialog").dialog({autoOpen:false,modal:true,buttons:{"Set new BPM":function(){var j=$("#bpmForm").val();Anzu.player.changeBPM(j);$("#bpmButton > .ui-button-text").html("BPM="+j);$(this).dialog("close")},Cancel:function(){$(this).dialog("close")}},close:function(){}});$("#addToneDialog").dialog({autoOpen:false,modal:true,buttons:{"Load this tone":function(){var j=$("#userToneForm").val();if(j.match(/\.js/)){$("#userToneFormHelper").text("Now loading ...");Anzu.player.addUserTone(j,function(){$("#addToneDialog").dialog("close")})}else $("#userToneFormHelper").addClass("ui-state-highlight").text("Invalid URL. Tone file must be JavaScript file. (*.js only)")},
Cancel:function(){$(this).dialog("close")}},close:function(){}});$("#exportDialog").dialog({autoOpen:false,modal:true});$("#trackVolume").slider({value:50,range:"min",stop:function(){var j=$("#trackVolume").slider("value")/100;Anzu.player.changeVolume(j)},animate:true});Anzu.player.refreshTone()});
Anzu.player=function(){function j(){d=$("iframe")[0].contentWindow.Anzu.ui.getCurrentTime()}function g(){return $("iframe")[0].contentWindow.Anzu.ui.getTrack()}var d=0,b=0,h=false,e="",c="";return{play:function(){var a=$("iframe")[0].contentWindow;j();Anzu.player.score.updateTrack(b,$("iframe")[0].contentWindow.Anzu.ui.getTrack());Anzu.player.score.setCallback(a.Anzu.ui.startAnimation);Anzu.player.score.setAfterCallback(function(){h=false});Anzu.player.score.play(d)},stop:function(){Anzu.player.score.stop(d);
$("iframe")[0].contentWindow.Anzu.ui.stopAnimation()},playstop:function(){h?this.stop():this.play();h=!h},set:function(){$("iframe")[0].contentWindow.Anzu.ui.setScore(Anzu.player.score);var a=Anzu.player.score.getTrack(b);$("iframe")[0].contentWindow.Anzu.ui.setTrack(a);$('input[name="tone"]').each(function(k,l){l.checked=l.value===a.getTone()?true:false});$("#trackVolume").slider("value",a.getVolume()*100);$("#onionCheckBox")[0].checked=a.isOnion();$("#onionCheckBox").button("refresh");$("#toneSelect").button("destroy");
$("#toneSelect").buttonset()},setEventManager:function(){$("iframe")[0].contentWindow.Anzu.eventManager=Anzu.eventManager;$("iframe")[0].contentWindow.Anzu.tone=Anzu.tone},moveBar:function(a){$("iframe")[0].contentWindow.Anzu.ui.moveBar(a)},changeTone:function(){var a=$('input[name="tone"]:checked').val();$("iframe")[0].contentWindow.Anzu.ui.changeTone(a);Anzu.eventManager.add("changeTone",a)},changeVolume:function(a){Anzu.player.score.getTrack(b).setVolume(a);Anzu.eventManager.add("changeVolume",
a)},selectTrack:function(a){b=parseInt(a.value)-1;this.set();$("#tracklist > li").each(function(k,l){l.className=""});a.className="current";Anzu.eventManager.changeCurrentTrack(b);return false},exportAsURL:function(a){Anzu.player.score.updateTrack(b,g());var k=Anzu.player.score.dump();return'http://anzutone.appspot.com/editor.html?load={"name":"'+encodeURI(a.name)+'","comment":"'+encodeURI(a.comment)+'","version":"'+a.version+'","score":'+k+"}"},openExportDialog:function(){var a=this.exportAsURL({name:"Anzu",
comment:"first",version:Anzu.core.version});$("#exportDialog").dialog("open");$("#exportDialogURL").html("I save your score <a href='"+encodeURI(a)+"'>this url</a>.<br><br>Bookmark it!")},load:function(a){try{var k=JSON.parse(a)}catch(l){alert("Parse Error. I cannot load this URL.")}e=k.name;c=k.comment;Anzu.eventManager.setDivID(k.score.maxID+1);Anzu.player.score=Anzu.Score(k.score);$("#bpmInput").val(Anzu.player.score.bpm);b=d=0;Anzu.player.set();$("#bpmForm").val(Anzu.player.score.bpm);$("#bpmButton > .ui-button-text").html("BPM="+
Anzu.player.score.bpm)},parseURL:function(){var a;if(document.location.href.match(/.+?load=(.+)/)){a=RegExp.$1;Anzu.player.load(decodeURI(a))}else this.set()},changeBPM:function(a){a=parseFloat(a);if(!(a<=0||a===NaN)){Anzu.player.score.changeBPM(a);Anzu.eventManager.add("changeBPM",a)}},frameLoaded:function(){Anzu.player.setEventManager();Anzu.eventManager.init();Anzu.player.parseURL()},refreshTone:function(){$("#toneSelect").html("");var a,k=Anzu.tone.getToneList();k.sort();var l,m=k.length;for(l=
0;l<m;l++){a=k[l];var n;n=a.split(".")[0]==="Anzu"?a.split(".")[1]:a;$("#toneSelect").append($("<input>").attr("type","radio").attr("name","tone").attr("id","radio."+a).attr("value",a)).append($("<label>").attr("for","radio."+a).html(n))}$("#toneSelect").buttonset()},addUserTone:function(a,k){Anzu.tone.addUserTone(a,function(){k()},function(l){$("#userToneFormHelper").html("Error!!<br>"+l)})},setOnion:function(a){Anzu.player.score.getTrack(b).setOnion(a)}}}();Anzu.ui=function(){var j=["Ad","Ad#","Bd","Cd","Cd#","Dd","Dd#","Ed","Fd","Fd#","Gd","Gd#"],g={},d={},b,h,e,c;e=j.length;c=0;for(b=1;b<=9;b++)for(h=0;h<e;h++){g[1920-c+40]=j[h].replace("d",b.toString(10));d[j[h].replace("d",b.toString(10))]=1920-c+40;c+=20}return{killBuffer:[],divID:0,browser:IsGecko()?0:1,posKeyList:g,posKeyRev:d,defualtNoteLen:98}}();
Anzu.ui.initPianorole=function(j){function g(f){var i={};i.width=f.length*100;i.left=f.begin*100;i.top=w[f.key];return c(i,f)}function d(f,i){if(t!==i){i.anzuHelper={};i.anzuHelper.x=parseInt(t.style.left)-parseInt(i.style.left);i.anzuHelper.y=parseInt(t.style.top)-parseInt(i.style.top)}}function b(f,i){if(t!==i){i.style.left=parseInt(t.style.left)-i.anzuHelper.x+"px";i.style.top=parseInt(t.style.top)-i.anzuHelper.y+"px"}}function h(f,i){p.changeNote(i)}function e(f){var i=new Date,r=Math.floor(f.pageY/
20)*20;if(H!==r){f=v[Math.floor(f.pageY/20)*20];Anzu.ShortAudio(0.3,f);M=i;H=r}}function c(f,i){var r,s,D,E;if(i){s=i.divID;r=i;D=f.top;E=f.left}else{s=Anzu.eventManager.getDivID();Anzu.eventManager.incDivID();r=new Anzu.Note;p.addNote(r);D=Math.floor(f.top/20)*20+1;E=Math.floor(f.left/12.5)*12.5}f=$("<div>").addClass(q).attr("style","width: "+f.width+"px; height: 17px; margin 0px 20px 20px 0px;position: absolute; opacity: 0.0;top:"+D+"px;left:"+E+"px;").attr("id",s+"AnzutoneNoteDiv").resizable({maxHeight:17,
minHeight:17,stop:function(){Anzu.ui.defualtNoteLen=parseInt(this.style.width,10);p.changeNote(this)}}).draggable({grid:[12.5,20],start:function(x){var F=$("#role > .ui-selected");t=this;F.each(d);e(x)},drag:function(x){var F=$("#role > .ui-selected");t=this;F.each(b);e(x)},stop:function(){var x=$("#role > .ui-selected");t=this;x.each(b);x.each(h);p.changeNote(this)}});f.animate({opacity:0.9},150);r.setDiv(f[0]);i||Anzu.eventManager.add("addNote",r);return f}function a(f){var i=$(f);p.deleteNoteFromDiv(f);
i.draggable("destroy");i.resizable("destroy");i.remove()}function k(f){Anzu.ui.killBuffer=[];var i=1E6;f.each(function(r,s){if(i>parseInt(s.style.left))i=parseInt(s.style.left)});f.each(function(r,s){$(s);Anzu.ui.killBuffer.push({top:parseInt(s.style.top),width:parseInt(s.style.width),left:parseInt(s.style.left)-i})})}function l(f){var i;i=f._notes();for(f=0;f<i.length;f++)m(i[f])}function m(f){var i={};i.width=f.length*100;i.left=f.begin*100;i.top=w[f.key];$("<div>").addClass(q).attr("style","width: "+
i.width+"px; height: 17px; margin 0px 20px 20px 0px;position: absolute; opacity: 0.3;top:"+i.top+"px;left:"+i.left+"px;").appendTo($("#role"))}function n(){var f=parseInt($("#bar")[0].style.left);f=(new Date-I)/1E3/J*(z-A);$("#bar")[0].style.left=f+A+"px";f>z+0.2&&o();document.body.scrollLeft=K+f}function o(){clearInterval(B);var f=parseInt($("#bar")[0].style.left);$("#bar")[0].style.left=Math.ceil(f/12.5)*12.5+"px";B=null}$("#role");var q="ui-widget-header",p=j;Anzu.ui.divID=Anzu.ui.divID?Anzu.ui.divID:
0;Anzu.ui.track=p;var v=Anzu.ui.posKeyList,w=Anzu.ui.posKeyRev;$(window).unbind("dblclick");$(window).unbind("keydown");$(document).selectable("destroy");$("#role > .ui-widget-header").each(function(f,i){var r=$(i);r.animate({opacity:0},200,"linear",function(){r.draggable("destroy");r.resizable("destroy");r.remove()})});var u,t,M=new Date,H;u=p._notes().length;var C=p._notes();for(j=0;j<u;j++)g(C[j]).appendTo($("#role"));C=Anzu.ui.score.getOnionTracks();var G;u=C.length;for(j=0;j<u;j++){G=C[j];G!==
p&&l(G)}$(window).dblclick(function(f){c({top:f.pageY,left:f.pageX,width:Anzu.ui.defualtNoteLen}).appendTo($("#role"))});$(window).keydown(function(f){switch(f.keyCode){case 8:case 46:f=$("#role > .ui-selected");f.each(function(r,s){a(s)});break;case 67:if(!f.ctrlKey)return;f=$("#role > .ui-selected");if(f.length===0)return;k(f);break;case 86:case 89:f=parseInt($("#bar")[0].style.left);var i;for(i=0;i<Anzu.ui.killBuffer.length;i++){Anzu.ui.killBuffer[i].left+=f;c(Anzu.ui.killBuffer[i]).appendTo($("#role"))}break;
case 87:case 88:f=$("#role > .ui-selected");f.each(function(r,s){a(s)});if(f.length===0)return;k(f);break}});$(document).selectable({selected:function(f,i){f=i.selected;f.style.position&&f.id&&$(f).addClass("anzu-note-selected")},unselected:function(f,i){i.unselected.style.position&&$(i.unselected).removeClass("anzu-note-selected")},start:function(f){window.focus();e(f)},filter:"#role > [id]"});var y=$("#barTooltip")[0],L=$("#barTooltipInner")[0];$("#bar").draggable({axis:"x",grid:[12.5,1],start:function(f){y.style.top=
f.pageY-20+"px";y.style.left=f.pageX+"px";L.innerHTML="&nbsp;"+Math.floor(f.pageX/400)+" + "+f.pageX%400/100;y.style.display="block"},drag:function(f){var i=parseInt($("#bar")[0].style.left);y.style.top=f.pageY-20+"px";y.style.left=i+"px";L.innerHTML="&nbsp;"+Math.floor(i/400)+" + "+i%400/100},stop:function(){y.style.display="none"}});Anzu.ui.getTrack=function(){return p};var z,B,I,A,J,K;Anzu.ui.startAnimation=function(f,i,r){if(i<=0)return false;if(B)return false;z=i*100;A=parseInt($("#bar")[0].style.left)+
r*100*Anzu.ui.browser;J=(z-A)/100*f;I=new Date;K=document.body.scrollLeft;B=setInterval(n,50);return true};Anzu.ui.stopAnimation=o;Anzu.ui.moveBar=function(f){var i=parseInt($("#bar")[0].style.left);if(i+f<0)$("#bar")[0].style.left="0px";else{i=Math.ceil((i+f)/100)*100;$("#bar")[0].style.left=i+"px";document.body.scrollLeft=i-400}};Anzu.ui.changeTone=function(f){p.setTone(f);Anzu.tone.setDefaultTone(f)};Anzu.ui.changeVolume=function(f){p.setVolume(f);p.setTone(tone);Anzu.tone.setDefaultTone(tone)};
Anzu.ui.changeTone(p.getTone());window.focus()};Anzu.ui.getCurrentTime=function(){return parseInt($("#bar")[0].style.left)/100};Anzu.ui.setTrack=function(j){Anzu.ui.initPianorole(j)};Anzu.ui.setScore=function(j){Anzu.ui.score=j};

