var Anzu={};Anzu.ui={};
Anzu.core=function(){function k(){var c={Cd:65.4,"Cd#":69.3,Dd:73.425,"Dd#":77.775,Ed:82.4,Fd:87.3,"Fd#":92.5,Gd:98,"Gd#":103.825,Ad:55,"Ad#":58.275,Bd:61.7375},d;for(d=2;d<=9;d++)for(var h in c)f[h.replace("d",d.toString(10))]=f[h.replace("d",(d-1).toString(10))]*2}var f={A1:55,"A1#":58.275,B1:61.7375,C1:65.4,"C1#":69.3,D1:73.425,"D1#":77.775,E1:82.4,F1:87.3,"F1#":92.5,G1:98,"G1#":103.825};k();return{convertToPitch:function(c){return f[c]},audioStream:$("body"),samplingRate:22050,version:"0.0.1"}}();
function IsGecko(){if(navigator)if(navigator.userAgent)if(navigator.userAgent.indexOf("Gecko/")!=-1)return true;return false};Anzu.wave=function(){function k(c){return String.fromCharCode(c>>0&255,c>>8&255)}function f(c){return String.fromCharCode(c>>0&255,c>>8&255,c>>16&255,c>>24&255)}return{generator:{createSquareSignal:function(c,d){var h,e,a;a=0;c=Math.round(c*22050);var b=d*2*Math.PI/22050;h=new Array(c);for(d=0;d<c;d++){e=Math.sin(a);e=e>0?0.7:-0.7;h[d]=~~(e*32767);a+=b}return h},createSinSignal:function(c,d){var h,e,a;a=0;c=Math.round(c*22050);var b=d*2*Math.PI/22050;h=new Array(c);for(d=0;d<c;d++){e=Math.sin(a);
h[d]=~~(e*32767);a+=b}return h},createSawtoothSignal:function(c,d){var h,e,a;a=0;c=Math.round(c*22050);var b=22050/d;h=new Array(c);for(d=0;d<c;d++){if(a>b)a-=b;e=a*2/b-1;h[d]=~~(e*32767);a+=1}return h},createTriangleSignal:function(c,d){var h,e,a;a=0;c=Math.round(c*22050);var b=22050/d;h=new Array(c);for(d=0;d<c;d++){if(a>b)a-=b;e=a*2/b-1;e=(Math.abs(e)-0.5)*2;h[d]=~~(e*32767);a+=1}return h},createWhiteNoiseSignal:function(c){var d,h,e;c=Math.round(c*22050);h=new Array(c);for(d=0;d<c;d++){e=Math.random()*
2-1;h[d]=~~(e*32767)}return h}},mixSignal:function(c,d,h){var e,a,b;a=d.length;h=Math.floor(h);for(e=0;e<a;e++){b=c[e+h]+d[e];c[e+h]=b}},mixSignalV:function(c,d,h,e){var a,b,j;b=d.length;h=Math.floor(h);for(a=0;a<b;a++){j=c[a+h]+~~(d[a]*e);c[a+h]=j}},convertToBinary:function(c){var d,h,e;h=c.length;for(d=0;d<h;d++){e=c[d];e=e>393204?393204:e<-393204?-393204:e;c[d]=String.fromCharCode((e+393204)/786408*256)}return c.join("")},convertToURL:function(c){var d;d="WAVEfmt ";d+=f(16);d+=k(1);d+=k(1);d+=
f(22050);d+=f(22050);d+=k(1);d+=k(8);d+="data";var h;h=f(c.length);d+=h;h="RIFF";h+=f(d.length+c.length);return"data:audio/wav;base64,"+Base64.encode(h+d+c)}}}();Anzu.Score=function(){return function(k){if(typeof k==="string")try{k=JSON.parse(k)}catch(f){alert("Parse Error");console.log(f)}for(var c=[],d,h,e,a=0;a<k.tracks.length;a++)c[a]=Anzu.Track(k.tracks[a]);return{bpm:k.bpm,addTrack:function(b){c.push(b)},updateTrack:function(b,j){c[b]=j},setCallback:function(b){h=b},setAfterCallback:function(b){e=b},play:function(b){var j,m,l,n,o,q,p,v,w;w=Anzu.core.samplingRate;m=c.length;p=this.getEndTime();q=60/this.bpm;v=Math.ceil((p-b)*q*w);if(v<=0)v=1;n=new Array(v);
for(j=0;j<v;j++)n[j]=0;Anzu.mixer.init(n);Anzu.mixer.setCallback(function(){var u=Anzu.wave.convertToBinary(n);u=Anzu.wave.convertToURL(u);d=new Audio(u);Anzu.core.audioStream.append($(d));d.volume=1;u=u=o=n=null;if(h)var t=setInterval(function(){if(d.currentTime>0.1){clearInterval(t);h(q,p-b,d.currentTime/q)}},100);e&&setTimeout(function(){e();if(d){d.pause();d.src=undefined;$(d).remove()}},v/w*1E3+100);d.play()});for(j=0;j<m;j++){l=c[j];o=l.getSignalOpt(n,b,q)}Anzu.mixer.finishAddQueues()},stop:function(){d.pause();
$(d).remove()},getEndTime:function(){var b,j,m,l;j=c.length;for(b=l=0;b<j;b++){m=c[b];m=m.getLastNote();m=m.begin+m.length;if(m>l)l=m}return l},getTrack:function(b){return c[b]},dump:function(){return'{"tracks":['+c.map(function(b){return b.dump()}).join(",")+'],"bpm":'+this.bpm+',"maxID":'+this.getMaxID()+"}"},changeBPM:function(b){this.bpm=b},changeNote:function(b,j){var m,l,n;if(m=Anzu.cache.getNote(b)){if(m===j)return;l=j.split("~");if(l[1]===""){n=parseInt(l[0]);c[n].deleteNote(eval("("+m.split("~")[1]+
")"))}else{n=parseInt(l[0]);c[n].updateNote(b,l[1])}}else{l=j.split("~");if(l[1]==="")return;n=parseInt(l[0]);c[n].updateNote(b,l[1])}Anzu.cache.setNote(b,j)},getMaxID:function(){for(var b,j,m=b=0;m<c.length;m++){j=c[m].getMaxID();if(j>b)b=j}return b},getOnionTracks:function(){for(var b=[],j=0;j<c.length;j++)c[j].isOnion()&&b.push(c[j]);return b}}}}();
Anzu.Track=function(){return function(k){if(typeof k==="string")k=JSON.parse(k);var f,c,d=0.5,h=false;f=k.notes;for(var e=0;e<f.length;e++)f[e]=Anzu.Note(f[e]);if(k.tone.match(/\.js/)){c="Anzu.SequareWave";Anzu.tone.addUserTone(k.tone,function(a){c=a})}else c=k.tone;d=k.volume?Math.abs(k.volume)>1?0.5:k.volume:0.5;return{addNote:function(a){f.push(a)},deleteNote:function(a){for(var b=0;b<f.length;b++)if(f[b].divID==a.divID){f.splice(b,1);return}},deleteUnlinkNotes:function(){for(var a=f.length-1;a>=
0;a--)f[a].divID||f.splice(a,1)},getNote:function(a){for(var b=0;b<f.length;b++)if(f[b].divID==a)return f[b];return null},_notes:function(){return f},deleteNoteFromDiv:function(a){for(var b=0;b<f.length;b++)if(f[b].divID==parseInt(a.id,10)){Anzu.eventManager.add("deleteNote",f[b]);f.splice(b,1);return}},changeNote:function(a){for(var b=0;b<f.length;b++)if(f[b].divID==parseInt(a.id,10)){f[b].setDiv(a);Anzu.eventManager.add("changeNote",f[b]);return}},setTone:function(a){c=a},getTone:function(){return c},
getLastNote:function(){if(f.length===0)return Anzu.Note({begin:0,length:0,key:"A4"});f.sort(function(a,b){return a.begin+a.length-(b.begin+b.length)});return f[f.length-1]},getSignal:function(a,b){var j=Anzu.core.samplingRate,m,l,n,o,q,p;p=Anzu.tone.getTone(c);l=f.length;m=this.getLastNote();n=Math.ceil((m.begin+m.length)*b*j);m=new Array(n);for(o=0;o<n;o++)m[o]=0;for(o=0;o<l;o++){n=f[o];if(!(n.begin<a)){q=n.getSignal(p,b);Anzu.wave.mixSignal(m,q,(n.begin-a)*b*j)}}return m},getSignalOpt:function(a,
b,j){var m=Anzu.core.samplingRate,l,n,o,q,p;p=Anzu.tone.getTone(c);n=f.length;l=this.getLastNote();Math.ceil((l.begin+l.length)*j*m);if(typeof p==="function")for(l=0;l<n;l++){o=f[l];if(!(o.begin<b)){q=o.getSignal(p,j);Anzu.wave.mixSignalV(a,q,(o.begin-b)*j*m,d)}}else for(l=0;l<n;l++){o=f[l];if(!(o.begin<b)){q=l+"@"+o.begin+"@"+o.length;Anzu.mixer.addQueue({key:q,info:{start:(o.begin-b)*j*m,volume:d}});o.getSignalASync(p,j,q)}}return a},isOnion:function(){return h},setOnion:function(a){h=a},getVolume:function(){return d},
setVolume:function(a){d=a},getMaxID:function(){for(var a,b,j=a=0;j<f.length;j++){b=f[j].divID;if(b>a)a=b}return a},updateNote:function(a,b){for(var j=0;j<f.length;j++)if(f[j].divID==a){f[j]=Anzu.Note(eval("("+b+")"));return}f.push(Anzu.Note(eval("("+b+")")))},dump:function(){return'{"notes":['+f.map(function(a){return a.dump()}).join(",")+'],"tone":"'+Anzu.tone.getToneDumpName(c)+'","volume":'+d+"}"}}}}();
Anzu.Note=function(){return function(k){k=!k?{}:k;return{begin:k.begin,length:k.length,key:k.key,divID:k.divID,dirty:true,setDiv:function(f){this.div=f;var c,d,h;c=parseInt(f.style.top,10);d=parseInt(f.style.left,10);h=parseInt(f.style.width,10);this.begin=d/100;this.length=h/100;this.key=Anzu.ui.posKeyList[Math.floor((c+5)/20)*20];if(!this.divID)this.divID=parseInt(f.id,10)},getSignal:function(f,c){return f(c*this.length,Anzu.core.convertToPitch(this.key))},getSignalASync:function(f,c,d){f.call(c*
this.length,Anzu.core.convertToPitch(this.key),d)},dump:function(){return'{"begin":'+this.begin+',"length":'+this.length+',"key":"'+this.key+'","divID":"'+this.divID+'"}'}}}}();Anzu.mixer=function(){function k(){if(!h)return false;var e=0;for(var a in f)e++;return e===0}var f={},c,d,h=false;return{init:function(e){c=e;f={};h=false},addQueue:function(e){f[e.key]=e.info},finishAddQueues:function(){h=true;k()&&d()},finishQueue:function(e){var a=e.key;Anzu.wave.mixSignalV(c,e.signals,f[a].start,f[a].volume);delete f[a];k()&&d()},setCallback:function(e){d=e}}}();Anzu.tone=function(){function k(e){var a={};if(typeof e==="string"){e=e.split(",");var b,j=e.length;for(b=0;b<j-1;b++)e[b]=parseInt(e[b],10);b=e.pop();a.key=b;a.signals=e}else a=e;return a}var f={},c={},d=Anzu.wave.createSquareSignal,h={};f["Anzu.SquareWave"]=Anzu.wave.generator.createSquareSignal;f["Anzu.SineWave"]=Anzu.wave.generator.createSinSignal;f["Anzu.SawtoothWave"]=Anzu.wave.generator.createSawtoothSignal;f["Anzu.WhiteNoise"]=Anzu.wave.generator.createWhiteNoiseSignal;return{addTone:function(e,
a){f[e]=a},getToneList:function(){var e=[],a;for(a in f)e.push(a);for(a in c)e.push(a);return e},getToneDumpName:function(e){if(f[e])return e;else if(c[e])return h[e];return"Anzu.SequareWave"},getTone:function(e){var a=f[e];if(a)return a;else{var b=c[e];return b?{call:function(j,m,l){(function(n){parseInt(n);var o;b.onmessage=function(){return function(q){q=k(q.data);Anzu.mixer.finishQueue({key:q.key,signals:q.signals})}}(n);o=IsGecko()?0:1;b.postMessage(j+"|"+m+"|"+Anzu.core.samplingRate+"|"+n+"|"+
o)})(l)}}:Anzu.wave.createSquareSignal}},getDefaultTone:function(){return d},setDefaultTone:function(e){if(f[e])d=this.getTone(e);else if(c[e]){var a=c[e];d={call:function(b,j,m){a.onmessage=function(n){n=k(n.data).signals;b(n)};var l=IsGecko()?0:1;a.postMessage(j+"|"+m+"|"+Anzu.core.samplingRate+"|once|"+l)}}}return f["Anzu.SeguareWave"]},addUserTone:function(e,a,b){for(var j in h)h.key===e&&a(j);var m=new Worker("usertone.js");m.onmessage=function(l){l=l.data.split("@")[0];c[l]=m;h[l]=e;a&&a(l);
Anzu.player.refreshTone()};m.onerror=function(l){b(l.message)};m.postMessage("init|"+e)}}}();Anzu.ShortAudio=function(){return function(k,f){function c(n){e=Anzu.wave.convertToURL(Anzu.wave.convertToBinary(n));a=new Audio(e);b=$(a);j=Anzu.core.audioStream;m=k;h()}function d(){a.pause();a.loop=false;a=null;b[0].src=undefined;b.remove();m=j=b=null}function h(){j.append(b);a.volume=0.3;a.loop=false;a.play();j=null;setTimeout(d,Math.floor(m*1E3*1.2));m=null}var e,a,b,j,m;j=Anzu.core.audioStream;var l=Anzu.tone.getDefaultTone();f=Anzu.core.convertToPitch(f);if(typeof l!=="function"){l.call(c,
k,f);return{play:function(){}}}else{l=l(k,f);c(l)}f=l=l=e=null;return{play:h}}}();Anzu.ui=function(){var k=["Ad","Ad#","Bd","Cd","Cd#","Dd","Dd#","Ed","Fd","Fd#","Gd","Gd#"],f={},c={},d,h,e,a;e=k.length;a=0;for(d=1;d<=9;d++)for(h=0;h<e;h++){f[1920-a+40]=k[h].replace("d",d.toString(10));c[k[h].replace("d",d.toString(10))]=1920-a+40;a+=20}return{killBuffer:[],divID:0,browser:IsGecko()?0:1,posKeyList:f,posKeyRev:c,defualtNoteLen:98}}();
Anzu.ui.initPianorole=function(k){function f(g){var i={};i.width=g.length*100;i.left=g.begin*100;i.top=w[g.key];return a(i,g)}function c(g,i){if(t!==i){i.anzuHelper={};i.anzuHelper.x=parseInt(t.style.left)-parseInt(i.style.left);i.anzuHelper.y=parseInt(t.style.top)-parseInt(i.style.top)}}function d(g,i){if(t!==i){i.style.left=parseInt(t.style.left)-i.anzuHelper.x+"px";i.style.top=parseInt(t.style.top)-i.anzuHelper.y+"px"}}function h(g,i){p.changeNote(i)}function e(g){var i=new Date,r=Math.floor(g.pageY/
20)*20;if(H!==r){g=v[Math.floor(g.pageY/20)*20];Anzu.ShortAudio(0.3,g);M=i;H=r}}function a(g,i){var r,s,D,E;if(i){s=i.divID;r=i;D=g.top;E=g.left}else{s=Anzu.eventManager.getDivID();Anzu.eventManager.incDivID();r=new Anzu.Note;p.addNote(r);D=Math.floor(g.top/20)*20+1;E=Math.floor(g.left/12.5)*12.5}g=$("<div>").addClass(q).attr("style","width: "+g.width+"px; height: 17px; margin 0px 20px 20px 0px;position: absolute; opacity: 0.9;top:"+D+"px;left:"+E+"px;").attr("id",s+"AnzutoneNoteDiv").resizable({maxHeight:17,
minHeight:17,stop:function(){Anzu.ui.defualtNoteLen=parseInt(this.style.width,10);p.changeNote(this)}}).draggable({grid:[12.5,20],start:function(x){var F=$("#role > .ui-selected");t=this;F.each(c);e(x)},drag:function(x){var F=$("#role > .ui-selected");t=this;F.each(d);e(x)},stop:function(){var x=$("#role > .ui-selected");t=this;x.each(d);x.each(h);p.changeNote(this)}});r.setDiv(g[0]);i||Anzu.eventManager.add("addNote",r);return g}function b(g){var i=$(g);p.deleteNoteFromDiv(g);i.draggable("destroy");
i.resizable("destroy");i.remove()}function j(g){Anzu.ui.killBuffer=[];var i=1E6;g.each(function(r,s){if(i>parseInt(s.style.left))i=parseInt(s.style.left)});g.each(function(r,s){$(s);Anzu.ui.killBuffer.push({top:parseInt(s.style.top),width:parseInt(s.style.width),left:parseInt(s.style.left)-i})})}function m(g){var i;i=g._notes();for(g=0;g<i.length;g++)l(i[g])}function l(g){var i={};i.width=g.length*100;i.left=g.begin*100;i.top=w[g.key];$("<div>").addClass(q).attr("style","width: "+i.width+"px; height: 17px; margin 0px 20px 20px 0px;position: absolute; opacity: 0.3;top:"+
i.top+"px;left:"+i.left+"px;").appendTo($("#role"))}function n(){var g=parseInt($("#bar")[0].style.left);g=(new Date-I)/1E3/J*(z-A);$("#bar")[0].style.left=g+A+"px";g>z+0.2&&o();document.body.scrollLeft=K+g}function o(){clearInterval(B);var g=parseInt($("#bar")[0].style.left);$("#bar")[0].style.left=Math.ceil(g/12.5)*12.5+"px";B=null}$("#role");var q="ui-widget-header",p=k;Anzu.ui.divID=Anzu.ui.divID?Anzu.ui.divID:0;Anzu.ui.track=p;var v=Anzu.ui.posKeyList,w=Anzu.ui.posKeyRev;$(window).unbind("dblclick");
$(window).unbind("keydown");$(document).selectable("destroy");$("#role > .ui-widget-header").each(function(g,i){var r=$(i);p.getNote(parseInt(r.id,10));r.animate({opacity:0.9},0,"linear",function(){r.draggable("destroy");r.resizable("destroy");r.remove()})});var u,t,M=new Date,H;u=p._notes().length;var C=p._notes();for(k=0;k<u;k++)f(C[k]).appendTo($("#role"));C=Anzu.ui.score.getOnionTracks();var G;u=C.length;for(k=0;k<u;k++){G=C[k];G!==p&&m(G)}$(window).dblclick(function(g){a({top:g.pageY,left:g.pageX,
width:Anzu.ui.defualtNoteLen}).appendTo($("#role"))});$(window).keydown(function(g){switch(g.keyCode){case 8:case 46:g=$("#role > .ui-selected");g.each(function(r,s){b(s)});break;case 67:if(!g.ctrlKey)return;g=$("#role > .ui-selected");if(g.length===0)return;j(g);break;case 86:case 89:g=parseInt($("#bar")[0].style.left);var i;for(i=0;i<Anzu.ui.killBuffer.length;i++){Anzu.ui.killBuffer[i].left+=g;a(Anzu.ui.killBuffer[i]).appendTo($("#role"))}break;case 87:case 88:g=$("#role > .ui-selected");g.each(function(r,
s){b(s)});if(g.length===0)return;j(g);break}});$(document).selectable({selected:function(g,i){g=i.selected;g.style.position&&g.id&&$(g).addClass("anzu-note-selected")},unselected:function(g,i){i.unselected.style.position&&$(i.unselected).removeClass("anzu-note-selected")},start:function(g){window.focus();e(g)},filter:"#role > [id]"});var y=$("#barTooltip")[0],L=$("#barTooltipInner")[0];$("#bar").draggable({axis:"x",grid:[12.5,1],start:function(g){y.style.top=g.pageY-20+"px";y.style.left=g.pageX+"px";
L.innerHTML="&nbsp;"+Math.floor(g.pageX/400)+" + "+g.pageX%400/100;y.style.display="block"},drag:function(g){var i=parseInt($("#bar")[0].style.left);y.style.top=g.pageY-20+"px";y.style.left=i+"px";L.innerHTML="&nbsp;"+Math.floor(i/400)+" + "+i%400/100},stop:function(){y.style.display="none"}});Anzu.ui.getTrack=function(){return p};var z,B,I,A,J,K;Anzu.ui.startAnimation=function(g,i,r){if(i<=0)return false;if(B)return false;z=i*100;A=parseInt($("#bar")[0].style.left)+r*100*Anzu.ui.browser;J=(z-A)/
100*g;I=new Date;K=document.body.scrollLeft;B=setInterval(n,50);return true};Anzu.ui.stopAnimation=o;Anzu.ui.moveBar=function(g){var i=parseInt($("#bar")[0].style.left);if(i+g<0)$("#bar")[0].style.left="0px";else{i=Math.ceil((i+g)/100)*100;$("#bar")[0].style.left=i+"px";document.body.scrollLeft=i-400}};Anzu.ui.changeTone=function(g){p.setTone(g);Anzu.tone.setDefaultTone(g)};Anzu.ui.changeVolume=function(g){p.setVolume(g);p.setTone(tone);Anzu.tone.setDefaultTone(tone)};Anzu.ui.changeTone(p.getTone());
window.focus()};Anzu.ui.getCurrentTime=function(){return parseInt($("#bar")[0].style.left)/100};Anzu.ui.setTrack=function(k){Anzu.ui.initPianorole(k)};Anzu.ui.setScore=function(k){Anzu.ui.score=k};


