var Anzu={};Anzu.ui={};
Anzu.core=function(){function j(){var d={Cd:65.4,"Cd#":69.3,Dd:73.425,"Dd#":77.775,Ed:82.4,Fd:87.3,"Fd#":92.5,Gd:98,"Gd#":103.825,Ad:55,"Ad#":58.275,Bd:61.7375},c;for(c=2;c<=9;c++)for(var i in d)g[i.replace("d",c.toString(10))]=g[i.replace("d",(c-1).toString(10))]*2}var g={A1:55,"A1#":58.275,B1:61.7375,C1:65.4,"C1#":69.3,D1:73.425,"D1#":77.775,E1:82.4,F1:87.3,"F1#":92.5,G1:98,"G1#":103.825};j();return{convertToPitch:function(d){return g[d]},audioStream:$("body"),samplingRate:22050,version:"0.0.1"}}();
function IsGecko(){if(navigator)if(navigator.userAgent)if(navigator.userAgent.indexOf("Gecko/")!=-1)return true;return false};Anzu.wave=function(){function j(d){return String.fromCharCode(d>>0&255,d>>8&255)}function g(d){return String.fromCharCode(d>>0&255,d>>8&255,d>>16&255,d>>24&255)}return{generator:{createSquareSignal:function(d,c){var i,f,a;a=0;d=Math.round(d*22050);var b=c*2*Math.PI/22050;i=new Array(d);for(c=0;c<d;c++){f=Math.sin(a);f=f>0?0.7:-0.7;i[c]=~~(f*32767);a+=b}return i},createSinSignal:function(d,c){var i,f,a;a=0;d=Math.round(d*22050);var b=c*2*Math.PI/22050;i=new Array(d);for(c=0;c<d;c++){f=Math.sin(a);
i[c]=~~(f*32767);a+=b}return i},createSawtoothSignal:function(d,c){var i,f,a;a=0;d=Math.round(d*22050);var b=22050/c;i=new Array(d);for(c=0;c<d;c++){if(a>b)a-=b;f=a*2/b-1;i[c]=~~(f*32767);a+=1}return i},createTriangleSignal:function(d,c){var i,f,a;a=0;d=Math.round(d*22050);var b=22050/c;i=new Array(d);for(c=0;c<d;c++){if(a>b)a-=b;f=a*2/b-1;f=(Math.abs(f)-0.5)*2;i[c]=~~(f*32767);a+=1}return i},createWhiteNoiseSignal:function(d){var c,i,f;d=Math.round(d*22050);i=new Array(d);for(c=0;c<d;c++){f=Math.random()*
2-1;i[c]=~~(f*32767)}return i}},mixSignal:function(d,c,i){var f,a,b;a=c.length;i=Math.floor(i);for(f=0;f<a;f++){b=d[f+i]+c[f];d[f+i]=b}},mixSignalV:function(d,c,i,f){var a,b,k;b=c.length;i=Math.floor(i);for(a=0;a<b;a++){k=d[a+i]+~~(c[a]*f);d[a+i]=k}},convertToBinary:function(d){var c,i,f;i=d.length;for(c=0;c<i;c++){f=d[c];f=f>393204?393204:f<-393204?-393204:f;d[c]=String.fromCharCode((f+393204)/786408*256)}return d.join("")},convertToURL:function(d){var c;c="WAVEfmt ";c+=g(16);c+=j(1);c+=j(1);c+=
g(22050);c+=g(22050);c+=j(1);c+=j(8);c+="data";var i;i=g(d.length);c+=i;i="RIFF";i+=g(c.length+d.length);return"data:audio/wav;base64,"+Base64.encode(i+c+d)}}}();Anzu.ShortAudio=function(){return function(j,g){function d(n){f=Anzu.wave.convertToURL(Anzu.wave.convertToBinary(n));a=new Audio(f);b=$(a);k=Anzu.core.audioStream;m=j;i()}function c(){a.pause();a.loop=false;a=null;b[0].src=undefined;b.remove();m=k=b=null}function i(){k.append(b);a.volume=0.3;a.loop=false;a.play();k=null;setTimeout(c,Math.floor(m*1E3*1.2));m=null}var f,a,b,k,m;k=Anzu.core.audioStream;var l=Anzu.tone.getDefaultTone();g=Anzu.core.convertToPitch(g);if(typeof l!=="function"){l.call(d,
j,g);return{play:function(){}}}else{l=l(j,g);d(l)}g=l=l=f=null;return{play:i}}}();Anzu.tone=function(){function j(f){var a={};if(typeof f==="string"){f=f.split(",");var b,k=f.length;for(b=0;b<k-1;b++)f[b]=parseInt(f[b],10);b=f.pop();a.key=b;a.signals=f}else a=f;return a}var g={},d={},c=Anzu.wave.createSquareSignal,i={};g["Anzu.SquareWave"]=Anzu.wave.generator.createSquareSignal;g["Anzu.SineWave"]=Anzu.wave.generator.createSinSignal;g["Anzu.SawtoothWave"]=Anzu.wave.generator.createSawtoothSignal;g["Anzu.WhiteNoise"]=Anzu.wave.generator.createWhiteNoiseSignal;return{addTone:function(f,
a){g[f]=a},getToneList:function(){var f=[],a;for(a in g)f.push(a);for(a in d)f.push(a);return f},getToneDumpName:function(f){if(g[f])return f;else if(d[f])return i[f];return"Anzu.SequareWave"},getTone:function(f){var a=g[f];if(a)return a;else{var b=d[f];return b?{call:function(k,m,l){(function(n){parseInt(n);var o;b.onmessage=function(){return function(q){q=j(q.data);Anzu.mixer.finishQueue({key:q.key,signals:q.signals})}}(n);o=IsGecko()?0:1;b.postMessage(k+"|"+m+"|"+Anzu.core.samplingRate+"|"+n+"|"+
o)})(l)}}:Anzu.wave.createSquareSignal}},getDefaultTone:function(){return c},setDefaultTone:function(f){if(g[f])c=this.getTone(f);else if(d[f]){var a=d[f];c={call:function(b,k,m){a.onmessage=function(n){n=j(n.data).signals;b(n)};var l=IsGecko()?0:1;a.postMessage(k+"|"+m+"|"+Anzu.core.samplingRate+"|once|"+l)}}}return g["Anzu.SeguareWave"]},addUserTone:function(f,a,b){for(var k in i)i.key===f&&a(k);var m=new Worker("js/anzu/usertone.js");m.onmessage=function(l){l=l.data.split("@")[0];d[l]=m;i[l]=f;
a&&a(l);Anzu.player.refreshTone()};m.onerror=function(l){b(l.message)};m.postMessage("init|"+f)}}}();Anzu.Score=function(){return function(j){if(typeof j==="string")try{j=JSON.parse(j)}catch(g){alert("Parse Error");console.log(g)}for(var d=[],c,i,f,a=0;a<j.tracks.length;a++)d[a]=Anzu.Track(j.tracks[a]);return{bpm:j.bpm,addTrack:function(b){d.push(b)},updateTrack:function(b,k){d[b]=k},setCallback:function(b){i=b},setAfterCallback:function(b){f=b},play:function(b){var k,m,l,n,o,q,p,v,w;w=Anzu.core.samplingRate;m=d.length;p=this.getEndTime();q=60/this.bpm;v=Math.ceil((p-b)*q*w);if(v<=0)v=1;n=new Array(v);
for(k=0;k<v;k++)n[k]=0;Anzu.mixer.init(n);Anzu.mixer.setCallback(function(){var u=Anzu.wave.convertToBinary(n);u=Anzu.wave.convertToURL(u);c=new Audio(u);Anzu.core.audioStream.append($(c));c.volume=1;u=u=o=n=null;if(i)var t=setInterval(function(){if(c.currentTime>0.1){clearInterval(t);i(q,p-b,c.currentTime/q)}},100);f&&setTimeout(function(){f();if(c){c.pause();c.src=undefined;$(c).remove()}},v/w*1E3+100);c.play()});for(k=0;k<m;k++){l=d[k];o=l.getSignalOpt(n,b,q)}Anzu.mixer.finishAddQueues()},stop:function(){c.pause();
$(c).remove()},getEndTime:function(){var b,k,m,l;k=d.length;for(b=l=0;b<k;b++){m=d[b];m=m.getLastNote();m=m.begin+m.length;if(m>l)l=m}return l},getTrack:function(b){return d[b]},dump:function(){return'{"tracks":['+d.map(function(b){return b.dump()}).join(",")+'],"bpm":'+this.bpm+',"maxID":'+this.getMaxID()+"}"},changeBPM:function(b){this.bpm=b},getMaxID:function(){for(var b,k,m=b=0;m<d.length;m++){k=d[m].getMaxID();if(k>b)b=k}return b},getOnionTracks:function(){for(var b=[],k=0;k<d.length;k++)d[k].isOnion()&&
b.push(d[k]);return b}}}}();
Anzu.Track=function(){return function(j){if(typeof j==="string")j=JSON.parse(j);var g,d,c=0.5,i=false;g=j.notes;for(var f=0;f<g.length;f++)g[f]=Anzu.Note(g[f]);if(j.tone.match(/\.js/)){d="Anzu.SequareWave";Anzu.tone.addUserTone(j.tone,function(a){d=a})}else d=j.tone;c=j.volume?Math.abs(j.volume)>1?0.5:j.volume:0.5;return{addNote:function(a){g.push(a)},deleteNote:function(a){for(var b=0;g.length;b++)if(g[b]===a){g.splice(b,1);return}},deleteUnlinkNotes:function(){for(var a=g.length-1;a>=0;a--)g[a].divID||
g.splice(a,1)},_notes:function(){return g},deleteNoteFromDiv:function(a){for(var b=0;b<g.length;b++)if(g[b].divID===parseInt(a.id,10)){Anzu.eventManager.add("deleteNote",g[b]);g.splice(b,1);return}},changeNote:function(a){for(var b=0;b<g.length;b++)if(g[b].divID===parseInt(a.id,10)){g[b].setDiv(a);Anzu.eventManager.add("changeNote",g[b]);return}},setTone:function(a){d=a},getTone:function(){return d},getLastNote:function(){if(g.length===0)return Anzu.Note({begin:0,length:0,key:"A4"});g.sort(function(a,
b){return a.begin+a.length-(b.begin+b.length)});return g[g.length-1]},getSignal:function(a,b){var k=Anzu.core.samplingRate,m,l,n,o,q,p;p=Anzu.tone.getTone(d);l=g.length;m=this.getLastNote();n=Math.ceil((m.begin+m.length)*b*k);m=new Array(n);for(o=0;o<n;o++)m[o]=0;for(o=0;o<l;o++){n=g[o];if(!(n.begin<a)){q=n.getSignal(p,b);Anzu.wave.mixSignal(m,q,(n.begin-a)*b*k)}}return m},getSignalOpt:function(a,b,k){var m=Anzu.core.samplingRate,l,n,o,q,p;p=Anzu.tone.getTone(d);n=g.length;l=this.getLastNote();Math.ceil((l.begin+
l.length)*k*m);if(typeof p==="function")for(l=0;l<n;l++){o=g[l];if(!(o.begin<b)){q=o.getSignal(p,k);Anzu.wave.mixSignalV(a,q,(o.begin-b)*k*m,c)}}else for(l=0;l<n;l++){o=g[l];if(!(o.begin<b)){q=l+"@"+o.begin+"@"+o.length;Anzu.mixer.addQueue({key:q,info:{start:(o.begin-b)*k*m,volume:c}});o.getSignalASync(p,k,q)}}return a},isOnion:function(){return i},setOnion:function(a){i=a},getVolume:function(){return c},setVolume:function(a){c=a},getMaxID:function(){for(var a,b,k=a=0;k<g.length;k++){b=g[k].divID;
if(b>a)a=b}return a},dump:function(){return'{"notes":['+g.map(function(a){return a.dump()}).join(",")+'],"tone":"'+Anzu.tone.getToneDumpName(d)+'","volume":'+c+"}"}}}}();
Anzu.Note=function(){return function(j){j=!j?{}:j;return{begin:j.begin,length:j.length,key:j.key,divID:parseInt(j.id),setDiv:function(g){this.div=g;var d,c,i;d=parseInt(g.style.top,10);c=parseInt(g.style.left,10);i=parseInt(g.style.width,10);this.begin=c/100;this.length=i/100;this.key=Anzu.ui.posKeyList[Math.floor((d+5)/20)*20];this.divID=parseInt(g.id,10)},getSignal:function(g,d){return g(d*this.length,Anzu.core.convertToPitch(this.key))},getSignalASync:function(g,d,c){g.call(d*this.length,Anzu.core.convertToPitch(this.key),
c)},dump:function(){return'{"begin":'+this.begin+',"length":'+this.length+',"key":"'+this.key+'","id":"'+this.divID+'"}'}}}}();Anzu.ui=function(){var j=["Ad","Ad#","Bd","Cd","Cd#","Dd","Dd#","Ed","Fd","Fd#","Gd","Gd#"],g={},d={},c,i,f,a;f=j.length;a=0;for(c=1;c<=9;c++)for(i=0;i<f;i++){g[1920-a+40]=j[i].replace("d",c.toString(10));d[j[i].replace("d",c.toString(10))]=1920-a+40;a+=20}return{killBuffer:[],divID:0,browser:IsGecko()?0:1,posKeyList:g,posKeyRev:d,defualtNoteLen:98}}();
Anzu.ui.initPianorole=function(j){function g(e){var h={};h.width=e.length*100;h.left=e.begin*100;h.top=w[e.key];return a(h,e)}function d(e,h){if(t!==h){h.anzuHelper={};h.anzuHelper.x=parseInt(t.style.left)-parseInt(h.style.left);h.anzuHelper.y=parseInt(t.style.top)-parseInt(h.style.top)}}function c(e,h){if(t!==h){h.style.left=parseInt(t.style.left)-h.anzuHelper.x+"px";h.style.top=parseInt(t.style.top)-h.anzuHelper.y+"px"}}function i(e,h){p.changeNote(h)}function f(e){var h=new Date,r=Math.floor(e.pageY/
20)*20;if(H!==r){e=v[Math.floor(e.pageY/20)*20];Anzu.ShortAudio(0.3,e);M=h;H=r}}function a(e,h){var r,s,D,E;if(h){s=h.divID;r=h;D=e.top;E=e.left}else{s=Anzu.eventManager.getDivID();Anzu.eventManager.incDivID();r=new Anzu.Note;p.addNote(r);D=Math.floor(e.top/20)*20+1;E=Math.floor(e.left/12.5)*12.5}e=$("<div>").addClass(q).attr("style","width: "+e.width+"px; height: 17px; margin 0px 20px 20px 0px;position: absolute; opacity: 0.0;top:"+D+"px;left:"+E+"px;").attr("id",s+"AnzutoneNoteDiv").resizable({maxHeight:17,
minHeight:17,stop:function(){Anzu.ui.defualtNoteLen=parseInt(this.style.width,10);p.changeNote(this)}}).draggable({grid:[12.5,20],start:function(x){var F=$("#role > .ui-selected");t=this;F.each(d);f(x)},drag:function(x){var F=$("#role > .ui-selected");t=this;F.each(c);f(x)},stop:function(){var x=$("#role > .ui-selected");t=this;x.each(c);x.each(i);p.changeNote(this)}});e.animate({opacity:0.9},150);r.setDiv(e[0]);h||Anzu.eventManager.add("addNote",r);return e}function b(e){var h=$(e);p.deleteNoteFromDiv(e);
h.draggable("destroy");h.resizable("destroy");h.remove()}function k(e){Anzu.ui.killBuffer=[];var h=1E6;e.each(function(r,s){if(h>parseInt(s.style.left))h=parseInt(s.style.left)});e.each(function(r,s){$(s);Anzu.ui.killBuffer.push({top:parseInt(s.style.top),width:parseInt(s.style.width),left:parseInt(s.style.left)-h})})}function m(e){var h;h=e._notes();for(e=0;e<h.length;e++)l(h[e])}function l(e){var h={};h.width=e.length*100;h.left=e.begin*100;h.top=w[e.key];$("<div>").addClass(q).attr("style","width: "+
h.width+"px; height: 17px; margin 0px 20px 20px 0px;position: absolute; opacity: 0.3;top:"+h.top+"px;left:"+h.left+"px;").appendTo($("#role"))}function n(){var e=parseInt($("#bar")[0].style.left);e=(new Date-I)/1E3/J*(z-A);$("#bar")[0].style.left=e+A+"px";e>z+0.2&&o();document.body.scrollLeft=K+e}function o(){clearInterval(B);var e=parseInt($("#bar")[0].style.left);$("#bar")[0].style.left=Math.ceil(e/12.5)*12.5+"px";B=null}$("#role");var q="ui-widget-header",p=j;Anzu.ui.divID=Anzu.ui.divID?Anzu.ui.divID:
0;Anzu.ui.track=p;var v=Anzu.ui.posKeyList,w=Anzu.ui.posKeyRev;$(window).unbind("dblclick");$(window).unbind("keydown");$(document).selectable("destroy");$("#role > .ui-widget-header").each(function(e,h){var r=$(h);r.animate({opacity:0},200,"linear",function(){r.draggable("destroy");r.resizable("destroy");r.remove()})});var u,t,M=new Date,H;u=p._notes().length;var C=p._notes();for(j=0;j<u;j++)g(C[j]).appendTo($("#role"));C=Anzu.ui.score.getOnionTracks();var G;u=C.length;for(j=0;j<u;j++){G=C[j];G!==
p&&m(G)}$(window).dblclick(function(e){a({top:e.pageY,left:e.pageX,width:Anzu.ui.defualtNoteLen}).appendTo($("#role"))});$(window).keydown(function(e){switch(e.keyCode){case 8:case 46:e=$("#role > .ui-selected");e.each(function(r,s){b(s)});break;case 67:if(!e.ctrlKey)return;e=$("#role > .ui-selected");if(e.length===0)return;k(e);break;case 86:case 89:e=parseInt($("#bar")[0].style.left);var h;for(h=0;h<Anzu.ui.killBuffer.length;h++){Anzu.ui.killBuffer[h].left+=e;a(Anzu.ui.killBuffer[h]).appendTo($("#role"))}break;
case 87:case 88:e=$("#role > .ui-selected");e.each(function(r,s){b(s)});if(e.length===0)return;k(e);break}});$(document).selectable({selected:function(e,h){e=h.selected;e.style.position&&e.id&&$(e).addClass("anzu-note-selected")},unselected:function(e,h){h.unselected.style.position&&$(h.unselected).removeClass("anzu-note-selected")},start:function(e){window.focus();f(e)},filter:"#role > [id]"});var y=$("#barTooltip")[0],L=$("#barTooltipInner")[0];$("#bar").draggable({axis:"x",grid:[12.5,1],start:function(e){y.style.top=
e.pageY-20+"px";y.style.left=e.pageX+"px";L.innerHTML="&nbsp;"+Math.floor(e.pageX/400)+" + "+e.pageX%400/100;y.style.display="block"},drag:function(e){var h=parseInt($("#bar")[0].style.left);y.style.top=e.pageY-20+"px";y.style.left=h+"px";L.innerHTML="&nbsp;"+Math.floor(h/400)+" + "+h%400/100},stop:function(){y.style.display="none"}});Anzu.ui.getTrack=function(){return p};var z,B,I,A,J,K;Anzu.ui.startAnimation=function(e,h,r){if(h<=0)return false;if(B)return false;z=h*100;A=parseInt($("#bar")[0].style.left)+
r*100*Anzu.ui.browser;J=(z-A)/100*e;I=new Date;K=document.body.scrollLeft;B=setInterval(n,50);return true};Anzu.ui.stopAnimation=o;Anzu.ui.moveBar=function(e){var h=parseInt($("#bar")[0].style.left);if(h+e<0)$("#bar")[0].style.left="0px";else{h=Math.ceil((h+e)/100)*100;$("#bar")[0].style.left=h+"px";document.body.scrollLeft=h-400}};Anzu.ui.changeTone=function(e){p.setTone(e);Anzu.tone.setDefaultTone(e)};Anzu.ui.changeVolume=function(e){p.setVolume(e);p.setTone(tone);Anzu.tone.setDefaultTone(tone)};
Anzu.ui.changeTone(p.getTone());window.focus()};Anzu.ui.getCurrentTime=function(){return parseInt($("#bar")[0].style.left)/100};Anzu.ui.setTrack=function(j){Anzu.ui.initPianorole(j)};Anzu.ui.setScore=function(j){Anzu.ui.score=j};

